version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    ports:
      - 4100:4100
      - 4443:4443
    tty: true
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 27017
  redis:
    image: redis
    ports:
      - 6379
  zkill:
    build:
      context: ./
      dockerfile: zkill/Zkill.dockerfile
    ports:
      - 4200:4200
      - 4543:4543
    tty: true
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis